"""Regression: the demos are reproducible from their generators.

Each demo doc and its fixtures are generated by a build_*_demo.py module and
committed. Since the docs embed real tool output, a drift between the committed
doc and freshly-generated output means either the tool's output changed
(regenerate the demo) or the demo was hand-edited (don't — edit the generator).
These tests catch both.
"""

from __future__ import annotations

from pathlib import Path

from tools.impact.demo import build_overlap_demo as overlap_gen
from tools.impact.demo import build_timeline_demo as timeline_gen


REPO_ROOT = Path(__file__).resolve().parents[3]
EXERCISES = REPO_ROOT / "docs" / "exercises"
DEMO_ROOT = REPO_ROOT / "tools" / "impact" / "demo"


def _assert_reproducible(tmp_path, doc_committed, fixtures_committed,
                         out_doc, out_fixtures, regenerate_cmd):
    assert out_doc.read_text() == doc_committed.read_text(), (
        f"Committed demo doc {doc_committed.name} is stale — regenerate with "
        f"`{regenerate_cmd}`."
    )
    for committed in fixtures_committed.rglob("*.jsonld"):
        rel = committed.relative_to(fixtures_committed)
        regenerated = out_fixtures / rel
        assert regenerated.exists(), f"generator no longer produces {rel}"
        assert regenerated.read_text() == committed.read_text(), (
            f"Committed fixture {rel} is stale — regenerate the demo."
        )


def test_timeline_demo_matches_generator_output(tmp_path, monkeypatch):
    out_doc = tmp_path / "demo.md"
    out_fixtures = tmp_path / "timeline"
    monkeypatch.setattr(timeline_gen, "DEMO_DOC", out_doc)
    monkeypatch.setattr(timeline_gen, "TIMELINE_DIR", out_fixtures)
    timeline_gen.build()
    _assert_reproducible(
        tmp_path,
        EXERCISES / "dead-rule-lint-demo.md", DEMO_ROOT / "timeline",
        out_doc, out_fixtures,
        "./.venv/bin/python -m tools.impact.demo.build_timeline_demo",
    )


def test_overlap_demo_matches_generator_output(tmp_path, monkeypatch):
    out_doc = tmp_path / "demo.md"
    out_fixtures = tmp_path / "overlap"
    monkeypatch.setattr(overlap_gen, "DEMO_DOC", out_doc)
    monkeypatch.setattr(overlap_gen, "OVERLAP_DIR", out_fixtures)
    overlap_gen.build()
    _assert_reproducible(
        tmp_path,
        EXERCISES / "cross-policy-overlap-demo.md", DEMO_ROOT / "overlap",
        out_doc, out_fixtures,
        "./.venv/bin/python -m tools.impact.demo.build_overlap_demo",
    )
