"""Regression: the timeline demo is reproducible from the generator.

The demo doc and its fixtures are generated by build_timeline_demo.py and
committed. Since the doc embeds real tool output, a drift between the committed
doc and freshly-generated output means either the tool's output changed
(regenerate the demo) or the demo was hand-edited (don't — edit the generator).
This test catches both.
"""

from __future__ import annotations

from pathlib import Path

from tools.impact.demo import build_timeline_demo as gen


REPO_ROOT = Path(__file__).resolve().parents[3]
DEMO_DOC = REPO_ROOT / "docs" / "exercises" / "dead-rule-lint-demo.md"
TIMELINE = REPO_ROOT / "tools" / "impact" / "demo" / "timeline"


def test_demo_doc_matches_generator_output(tmp_path, monkeypatch):
    # Redirect the generator's outputs to a temp location and compare against
    # the committed files, so the test never mutates the working tree.
    out_doc = tmp_path / "demo.md"
    out_timeline = tmp_path / "timeline"
    monkeypatch.setattr(gen, "DEMO_DOC", out_doc)
    monkeypatch.setattr(gen, "TIMELINE_DIR", out_timeline)

    gen.build()

    assert out_doc.read_text() == DEMO_DOC.read_text(), (
        "Committed demo doc is stale — regenerate with "
        "`./.venv/bin/python -m tools.impact.demo.build_timeline_demo`."
    )
    for committed in TIMELINE.rglob("*.jsonld"):
        rel = committed.relative_to(TIMELINE)
        regenerated = out_timeline / rel
        assert regenerated.exists(), f"generator no longer produces {rel}"
        assert regenerated.read_text() == committed.read_text(), (
            f"Committed fixture {rel} is stale — regenerate the demo."
        )
