-- ABAC column-mask emission for Stage 3 worked exercise.
--
-- Generated by hand from:
--   policy:abac-column-mask-clerk-redact (Policy A — Redact)
--   policy:abac-column-mask-clerk-hash   (Policy B — Hash)
-- using the post-ADR-014/016/018-021 Tessera shape and the verified
-- Databricks ABAC DDL syntax (scoping doc §6, Stage 1 verification).
--
-- The Databricks Tessera adapter is not yet built; this file represents
-- what the adapter would emit given these two policies and the
-- configured tag-taxonomy mapping (ADR-021) that translates
--   sensitivity:PIIClerk ↔ has_tag_value('abac_column', 'clerk')
-- and identity mapping that translates
--   group:bg_rls_demo_all_priority_ops ↔ `bg_rls_demo_all_priority_ops`.
--
-- Companion artifacts:
--   ../examples/abac-column-mask-policy-a.{tessera.yaml,jsonld}
--   ../examples/abac-column-mask-policy-b.{tessera.yaml,jsonld}
-- Diagnostic:    ../examples/abac-column-mask.diagnostic.md
-- Comparison:    ../examples/abac-column-mask.comparison.md
--
-- The two policies share matching predicate and principal binding.
-- They differ only in transformation. The cross-policy combination
-- question (ADR-019's α/β/γ) is observed by deploying both and
-- querying as a non-privileged principal.
--
-- Verified DDL ordering per Stage 1: COLUMN MASK → TO → [EXCEPT] →
-- FOR TABLES → [WHEN] → MATCH COLUMNS ... AS alias → ON COLUMN alias.

-- ─── Policy A — Redact ───────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION bg_rls_demo.tpch.tessera__abac_column_mask_clerk_redact__mask(val STRING)
RETURNS STRING
RETURN 'CLERK-REDACTED';

GRANT EXECUTE ON FUNCTION bg_rls_demo.tpch.tessera__abac_column_mask_clerk_redact__mask TO `account users`;

CREATE OR REPLACE POLICY tessera__abac_column_mask_clerk_redact
  ON CATALOG bg_rls_demo
  COMMENT 'Tessera ABAC column mask — policy:abac-column-mask-clerk-redact'
  COLUMN MASK bg_rls_demo.tpch.tessera__abac_column_mask_clerk_redact__mask
    TO `account users`
    EXCEPT `bg_rls_demo_all_priority_ops`
    FOR TABLES
    MATCH COLUMNS has_tag_value('abac_column', 'clerk') AS pii_clerk_col
    ON COLUMN pii_clerk_col;


-- ─── Policy B — Hash ─────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION bg_rls_demo.tpch.tessera__abac_column_mask_clerk_hash__mask(val STRING)
RETURNS STRING
RETURN sha2(val, 256);

GRANT EXECUTE ON FUNCTION bg_rls_demo.tpch.tessera__abac_column_mask_clerk_hash__mask TO `account users`;

CREATE OR REPLACE POLICY tessera__abac_column_mask_clerk_hash
  ON CATALOG bg_rls_demo
  COMMENT 'Tessera ABAC column mask — policy:abac-column-mask-clerk-hash'
  COLUMN MASK bg_rls_demo.tpch.tessera__abac_column_mask_clerk_hash__mask
    TO `account users`
    EXCEPT `bg_rls_demo_all_priority_ops`
    FOR TABLES
    MATCH COLUMNS has_tag_value('abac_column', 'clerk') AS pii_clerk_col
    ON COLUMN pii_clerk_col;


-- ─── Notes on emission choices ────────────────────────────────────────────
--
-- * Both policies attach at CATALOG scope (bg_rls_demo) per the policies'
--   appliesTo.scope. They auto-apply to every column in the catalog whose
--   abac_column tag value is 'clerk' — currently just o_clerk on orders_abac,
--   but the scope is intentionally broader to demonstrate scoped attachment.
--
-- * UDF parameter is named `val` (single-arg STRING → STRING). Databricks
--   ABAC passes the matched column's value as the first argument; additional
--   arguments come from the USING COLUMNS clause (unused here — neither
--   transformation needs other column values).
--
-- * For Policy A's UDF, the input `val` is ignored — Redact replaces the
--   value unconditionally with the literal 'CLERK-REDACTED'. The function
--   could equivalently be RETURN 'CLERK-REDACTED'; explicit val parameter
--   matches the canonical Databricks signature.
--
-- * For Policy B's UDF, sha2(val, 256) is the documented Databricks
--   built-in for SHA-256 over a STRING input. Returns a 64-char hex string.
--
-- * Both policies use `TO account users EXCEPT bg_rls_demo_all_priority_ops`.
--   This expresses the negated-complement default-handling: members of
--   the privileged group pass through (allow); everyone else (the
--   universal complement) gets the masked value.
--
-- * Both UDFs are GRANTed EXECUTE to `account users` per the column-mask
--   exercise's finding that GRANT is operationally necessary (see also
--   issue #10 policy-execute-grants — v1 candidate to formalize this in
--   the IR).
