-- ABAC row-filter emission for three-branch priority visibility.
--
-- Generated by hand from:
--   policy:abac-row-filter-priority
-- using the post-ABAC Tessera shape and the verified Databricks ABAC
-- ROW FILTER DDL form (per public docs).
--
-- The Databricks Tessera adapter is not yet built; this file represents
-- what the adapter would emit given this policy and the configured
-- tag-taxonomy mapping (ADR-021) that translates
--   acme:rowDiscriminator: orderpriority ↔ has_tag_value('abac_column', 'orderpriority')
--
-- Companion artifacts:
--   ../examples/abac-row-filter-priority.tessera.yaml / .jsonld
-- Diagnostic:  ../examples/abac-row-filter-priority.diagnostic.md
-- Comparison:  ../examples/abac-row-filter-priority.comparison.md
--
-- Mechanism: this is Mechanism B (CASE inside the UDF). Three branches
-- cannot be expressed via Databricks' binary TO/EXCEPT principal
-- binding, so Tessera's clean three-rule IR compiles to a single UDF
-- with branching logic. See inputs §5 for the design observation.
--
-- Verified ROW FILTER DDL ordering per public docs:
--   ROW FILTER fn TO ... [EXCEPT ...] FOR TABLES [WHEN ...]
--     [MATCH COLUMNS ... [AS alias]] [USING COLUMNS (alias)]
-- UDF returns BOOLEAN (true = visible).

-- ─── The row filter UDF ──────────────────────────────────────────────────
-- Takes the matched column's value (via USING COLUMNS); returns BOOLEAN
-- indicating row visibility. Ordering of the CASE branches encodes
-- Tessera's first-match rule order from the IR: most-permissive first.

CREATE OR REPLACE FUNCTION acme.tpch.tessera__abac_row_filter_priority__filter(priority STRING)
RETURNS BOOLEAN
RETURN
  CASE
    WHEN is_account_group_member('acme_all_priority_ops')  THEN TRUE
    WHEN is_account_group_member('acme_high_priority_ops') THEN priority IN ('1-URGENT', '2-HIGH')
    ELSE                                                               priority IN ('3-MEDIUM', '4-NOT SPECIFIED', '5-LOW')
  END;

GRANT EXECUTE ON FUNCTION acme.tpch.tessera__abac_row_filter_priority__filter TO `account users`;

-- ─── The ABAC policy ─────────────────────────────────────────────────────
-- Attaches at catalog scope. MATCH COLUMNS selects the row-discriminator
-- column (whichever column in scope is tagged abac_column=orderpriority).
-- USING COLUMNS passes the matched column's value to the row-filter UDF.
-- TO `account users` is broad — the UDF handles the principal branching
-- internally (Mechanism B).

CREATE OR REPLACE POLICY tessera__abac_row_filter_priority
  ON CATALOG acme
  COMMENT 'Tessera ABAC row filter — policy:abac-row-filter-priority'
  ROW FILTER acme.tpch.tessera__abac_row_filter_priority__filter
    TO `account users`
    FOR TABLES
    MATCH COLUMNS has_tag_value('abac_column', 'orderpriority') AS priority_col
    USING COLUMNS (priority_col);


-- ─── Notes on emission choices ────────────────────────────────────────────
--
-- * Mechanism B (CASE inside the UDF) is forced here because three
--   branches don't fit Mechanism A's binary TO/EXCEPT. The prior
--   ABAC column-mask exercise discussed the Mechanism A vs B tradeoff;
--   for three-branch row filters, B is the only natural choice.
--
-- * The IR's `defaultStrategy: negated-complement` and the implicit-
--   first-match rule ordering both collapse into the CASE expression's
--   evaluation order at the SQL layer. An IR-equivalent
--   `explicit-baseline-group` Policy would compile to the same SQL.
--   The distinction is preserved in the IR for audit/intent purposes
--   but is lost at emission. See diagnostic §4.3.
--
-- * The MATCH COLUMNS predicate is `has_tag_value('abac_column', 'orderpriority')`.
--   The alias `priority_col` is the policy-local handle for the matched
--   column; USING COLUMNS passes its value as the function argument
--   `priority`.
--
-- * Currently the only column in the catalog tagged `abac_column=orderpriority`
--   is `acme.tpch.orders_abac.o_orderpriority`, so the policy
--   effectively applies just to that one table. Tagging additional
--   columns the same way would extend the policy to those tables
--   automatically — the catalog-scope attachment is the value
--   proposition of ABAC.
--
-- * GRANT EXECUTE is emitted defensively (per issue #10's framing).
--   Without it, non-owner principals would hit PERMISSION_DENIED when
--   their queries trigger the row filter.
