-- ACL-driven row visibility on bg_rls_demo.tpch.orders_rls_acl — Databricks emission.
--
-- Generated by hand from:
--   policy:acl-row-visibility (single rule, byDataset + existsInDataset)
-- using the Policy container shape (ADR-014). The Databricks Tessera adapter
-- is not yet built; this file represents what the adapter would emit when
-- implemented per the v0 IR plus the adapter's knowledge of the two-table
-- ACL pattern.
--
-- Companion artifacts: ../examples/acl-row-visibility-policy.{tessera.yaml,jsonld}
-- Diagnostic:          ../examples/acl-row-visibility.diagnostic.md
--
-- Mechanics: a single row filter function. For each row of the protected
-- table, the function checks (via EXISTS) whether there is a join path
-- from current_user() through rls_acl_mapping → rls_priority_acl whose
-- orderpriority matches the row's o_orderpriority.
--
-- Note on the v0 IR's representation of this pattern: PrincipalSetFromTable
-- models a single ACL table; the codename indirection here requires a
-- second table (rls_priority_acl). The IR carries the second table in the
-- `existsInDataset` condition operand, but v0 does not formalize the
-- cross-table join semantics. The adapter compiles the full join from
-- the structural shape declared in the policy plus its knowledge of the
-- pattern. See the diagnostic §4.1 for the full discussion.

CREATE OR REPLACE FUNCTION bg_rls_demo.tpch.tessera__acl_row_visibility__row_filter(o_orderpriority STRING)
RETURNS BOOLEAN
RETURN EXISTS (
  SELECT 1
  FROM bg_rls_demo.tpch.rls_acl_mapping m
  JOIN bg_rls_demo.tpch.rls_priority_acl p
    ON m.code_name = p.code_name
  WHERE lower(trim(m.username)) = lower(trim(current_user()))
    AND p.orderpriority = o_orderpriority
);

-- Attach the filter to the protected table.

ALTER TABLE bg_rls_demo.tpch.orders_rls_acl
  SET ROW FILTER bg_rls_demo.tpch.tessera__acl_row_visibility__row_filter
  ON (o_orderpriority);
