-- Column mask on acme.tpch.orders.o_clerk — Databricks emission.
--
-- Generated by hand from:
--   policy:column-mask-orders-clerk (single rule + Redact defaultBranch)
-- using the Policy container shape (ADR-014) and the structured
-- TransformationInstance form (ADR-016).
--
-- Companion artifacts: ../examples/column-mask-orders-clerk-policy.{tessera.yaml,jsonld}
-- Diagnostic:          ../examples/column-mask-orders-clerk.diagnostic.md
-- Comparison:          ../examples/column-mask-orders-clerk.comparison.md
--
-- The Databricks Tessera adapter is not yet built; this file represents
-- what the adapter would emit given this policy and standard identity
-- conventions on Databricks. The emission targets the pre-ABAC
-- ALTER COLUMN ... SET MASK mechanism (matching the existing
-- implementation), not the newer CREATE POLICY ... COLUMN MASK ...
-- MATCH COLUMNS form which is the subject of the deferred ABAC
-- Stage 3 exercise.
--
-- Structurally negated-complement: one explicit branch for the
-- full-access group, an unconditional ELSE for everyone else. The
-- ELSE clause carries the Redact transformation declared in the
-- policy's defaultBranch field.

CREATE OR REPLACE FUNCTION acme.tpch.tessera__column_mask_orders_clerk__mask(o_clerk STRING)
RETURNS STRING
RETURN
  CASE
    WHEN is_account_group_member('orders_full_access') THEN o_clerk
    ELSE 'CLERK-REDACTED'
  END;

GRANT EXECUTE ON FUNCTION acme.tpch.tessera__column_mask_orders_clerk__mask TO `account users`;

-- Attach the mask to the protected column.

ALTER TABLE acme.tpch.orders
  ALTER COLUMN o_clerk
  SET MASK acme.tpch.tessera__column_mask_orders_clerk__mask;
