-- Group-based row visibility on acme.tpch.orders — Databricks emission.
--
-- Generated by hand from:
--   policy:group-row-visibility-policy-a  (explicit-baseline-group, 3 rules)
--   policy:group-row-visibility-policy-b  (negated-complement, 2 rules + defaultBranch)
-- both using the Policy container shape introduced in ADR-014. SQL emission
-- itself is structurally unchanged from the pre-ADR-014 form because the
-- container's policy-level metadata lowers identically; what changed is the
-- source IR's clarity, not the target SQL.
--
-- The Databricks Tessera adapter is not yet built; this file represents
-- what the adapter would emit when implemented per the v0 IR.
-- Companion artifacts: ../examples/group-row-visibility-policy-{a,b}.{tessera.yaml,jsonld}
-- Diagnostic: ../examples/group-row-visibility.diagnostic.md
--
-- Two row filter functions are defined below — one per Tessera policy.
-- Unity Catalog allows only one row filter on a table at a time; the
-- deployment workflow chooses A or B.

-- ──────────────────────────────────────────────────────────────────────────
-- Policy A — explicit-baseline-group
-- ──────────────────────────────────────────────────────────────────────────
-- defaultStrategy: explicit-baseline-group
-- baselineGroup:   account users
--
-- The default branch is the explicit WHEN clause keyed off `account users`.
-- The trailing ELSE FALSE is a fail-closed safeguard: it covers principals
-- who are not even members of `account users` (rare in practice, but the
-- strategy's audit semantics require us not to silently grant them
-- visibility). Per inputs §5.7, this also handles the case where
-- is_account_group_member() cannot determine membership.

CREATE OR REPLACE FUNCTION acme.tpch.tessera__group_row_visibility_policy_a__row_filter(o_orderpriority STRING)
RETURNS BOOLEAN
RETURN
  CASE
    WHEN is_account_group_member('acme_all_priority_ops')  THEN TRUE
    WHEN is_account_group_member('acme_high_priority_ops') THEN o_orderpriority IN ('1-URGENT', '2-HIGH')
    WHEN is_account_group_member('account users')                 THEN o_orderpriority IN ('3-MEDIUM', '4-NOT SPECIFIED', '5-LOW')
    ELSE FALSE
  END;

-- ──────────────────────────────────────────────────────────────────────────
-- Policy B — negated-complement
-- ──────────────────────────────────────────────────────────────────────────
-- defaultStrategy: negated-complement (no baselineGroup)
--
-- The default branch is the ELSE clause; the negated-complement intent is
-- expressed by the ELSE rather than by a third explicit WHEN. This is the
-- readable form preferred by inputs §7.3 and the structural shape mirrored
-- by the existing implementation (the Phase 3 comparison target).
--
-- Note that the adapter recognized the (negated-complement + small set of
-- restrictive rules + explicit default-complement rule) pattern and folded
-- the third rule into the ELSE. The naive emission would instead produce
-- a third WHEN with `NOT is_account_group_member(...) AND NOT
-- is_account_group_member(...) AND ...`. See diagnostic §"Adapter
-- quality-of-output".

CREATE OR REPLACE FUNCTION acme.tpch.tessera__group_row_visibility_policy_b__row_filter(o_orderpriority STRING)
RETURNS BOOLEAN
RETURN
  CASE
    WHEN is_account_group_member('acme_all_priority_ops')  THEN TRUE
    WHEN is_account_group_member('acme_high_priority_ops') THEN o_orderpriority IN ('1-URGENT', '2-HIGH')
    ELSE                                                               o_orderpriority IN ('3-MEDIUM', '4-NOT SPECIFIED', '5-LOW')
  END;

-- ──────────────────────────────────────────────────────────────────────────
-- Attachment to the protected table
-- ──────────────────────────────────────────────────────────────────────────
-- Only one row filter may be active on a table at a time. Choose A or B.
-- The Phase 3 comparison target is Policy B; that is the default below.

ALTER TABLE acme.tpch.orders
  SET ROW FILTER acme.tpch.tessera__group_row_visibility_policy_b__row_filter
  ON (o_orderpriority);

-- To switch to Policy A:
--   ALTER TABLE acme.tpch.orders DROP ROW FILTER;
--   ALTER TABLE acme.tpch.orders
--     SET ROW FILTER acme.tpch.tessera__group_row_visibility_policy_a__row_filter
--     ON (o_orderpriority);
